### ISSUE TITLE
stuff

### ISSUE THREAD

**Issue by mikki8** [jordon31/OnlySnap#12]
hi,

i like your script. but how abount to download statuses, streams and messages(inc. photos and videos) ?
and a way to run the script headless - passing -all parameter

**Comment by jordon31** [comment]
What do you mean by "headless - passing -all parameter"

**Comment by jordon31** [comment]
see that I put the option download all

**Comment by mikki8** [comment]
yes u have notived the option.
but its need to be completely without a user who is choosingto this point.
i let this script run automatically on my server

**Comment by jordon31** [comment]
Added the command "--all" just download directly all profiles.. Wait for the next update

**Comment by mikki8** [comment]
if you need some code for downloading messages https://github.com/k0rnh0li0/onlyfans-dl/pull/218

**Comment by jordon31** [comment]
done check new update
