### ISSUE TITLE
An error has occurred: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by kusti420** [jordon31/OnlySnap#19]
An error has occurred: 'str' object does not support item assignment
Traceback (most recent call last):
  File "K:\Downloads\onlyfans\onlyfans-dl-4\OnlySnap\OnlySnap.py", line 808, in <module>
    SELECTED_MODELS = select_sub()
                      ^^^^^^^^^^^^
  File "K:\Downloads\onlyfans\onlyfans-dl-4\OnlySnap\OnlySnap.py", line 295, in select_sub
    SUBS = get_subs()
           ^^^^^^^^^^
  File "K:\Downloads\onlyfans\onlyfans-dl-4\OnlySnap\OnlySnap.py", line 274, in get_subs
    sub['type'] = 'Payed'
    ~~~^^^^^^^^
TypeError: 'str' object does not support item assignment

Please try again.

tried python 3.9 3.11.4 and 3.12.0b4

**Comment by jordon31** [comment]
Hello.. I don't have this problem.. You can try to put to update the 'def get_subs' feature with this:

`def get_subs():
    total_subs = load_from_cache()
    
    if total_subs is None:
        SUB_LIMIT = 10
        offset = 0
        total_subs = []
        
        while True:
            params = {
                "type": "active",
                "sort": "desc",
                "field": "expire_date",
                "limit": str(SUB_LIMIT),
                "offset": str(offset)
            }
            
            response = api_request("/subscriptions/subscribes", getparams=params).json()
            subscriptions = response.get("list", [])
            if not subscriptions:
                break
            for sub in subscriptions:
                if 'currentSubscribePrice' in sub and sub['currentSubscribePrice'] == 0:
                    sub['type'] = 'Free'
                    # Check if user has a trial subscription
                    for subscribe in sub['subscribedByData']['subscribes']:
                        if 'type' in subscribe and subscribe['type'] == 'trial':
                            sub['type'] = 'Trial'
                else:
                    sub['type'] = 'Payed'
            
            total_subs.extend(subscriptions)
            offset += SUB_LIMIT
        
        save_to_cache(total_subs)

    return total_subs`

**Comment by jordon31** [comment]
thanks for this.. i fix
