### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mikki8** [jordon31/OnlySnap#21]
hi,

noticed a bug

<img width="854" alt="Screenshot (57)" src="https://github.com/jordon31/OnlySnap/assets/76606753/a8e88f9f-b69e-4c56-ad7d-b949997a9b9f">

**Comment by jordon31** [comment]
thanks for you report .. i fix

**Comment by mikki8** [comment]
not fixed for me - same error popping

**Comment by mikki8** [comment]
have you maybe a script or a idea how i migrate my files from the old to this with the good folder structure ?
