### ISSUE TITLE
bug #2

### ISSUE THREAD

**Issue by mikki8** [jordon31/OnlySnap#23]
hi,

this bug is still popping
<img width="854" alt="266664863-a8e88f9f-b69e-4c56-ad7d-b949997a9b9f" src="https://github.com/jordon31/OnlySnap/assets/76606753/af33f3b5-74be-452f-884c-8f47b5151762">

and have you a idea how i migrate my old data to this script with the nice folder structure ?

**Comment by jordon31** [comment]
Can you tell me the profile ID? (if it is public)

**Comment by mikki8** [comment]
brittanytaylorxxx

**Comment by wjm99** [comment]
Hi there. It turned out "No model subbed". But I had no idea what went wrong.

<img width="320" alt="image" src="https://github.com/jordon31/OnlySnap/assets/52388996/28656225-0219-483c-8476-e13385272481">

**Comment by jordon31** [comment]
> Hi there. It turned out "No model subbed". But I had no idea what went wrong.
> 
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/52388996/266858257-28656225-0219-483c-8476-e13385272481.png">


Just to add another issue, not all subscriptions shows over the menu..
