### ISSUE TITLE
'NoneType' / 'lower'

### ISSUE THREAD

**Issue by TheViperBR** [jordon31/OnlySnap#24]
Hi
This shows only for one model...

An error has occurred: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "E:\OnlySnap-main\OnlySnap.py", line 930, in <module>
    media_downloaded = download_posts(photo_posts, False, pbar)
  File "E:\OnlySnap-main\OnlySnap.py", line 492, in download_posts
    if not download_tagged_posts and "spin" in post.get("text", "").lower():
AttributeError: 'NoneType' object has no attribute 'lower'

Please try again.

**Comment by TheViperBR** [comment]
Just to add another issue, not all subscriptions shows over the menu..

**Comment by jordon31** [comment]
> Just to add another issue, not all subscriptions shows over the menu..

Send me the Auth file on Telegram and tell me 1-2 profiles that you can't see

"https://t.me/ocst892"

**Comment by S4SApp** [comment]
@jordon31 anyway we can get your help, we are in a bind on capturing info needed to auth so creators can use our platform. 

Sorry for writing here, didnt see another way. have been struggling with this for weeks
