### ISSUE TITLE
Check existing downloads using name without extension

### ISSUE THREAD

**Issue by hyoretsu** [jordon31/OnlySnap#25]
This should be a very specific use case, but a great/unique feature nonetheless. When checking for existing downloads, check for the name of the file alone, excluding extension.

Why? Because I just downloaded a profile that takes up 74GB of `.mp4` videos and 6GB of `.jpg` photos which I'm looking into converting to AV1 (commonly `.mkv`) and Jpeg XL (`.jxl`).

It'd be the best for data hoarders without forcing us to download all the files again and then deleting the existing ones.

**Comment by jordon31** [comment]
Hello... I already had an idea about this... but regarding the cache... which recognizes everything that has been downloaded and only makes API requests for the new content that the creator has added, without making all the unnecessary requests, especially for those who have many posts.

Certainly, this will be in the next update.
