### ISSUE TITLE
Unable to download video files

### ISSUE THREAD

**Issue by AnoCurly** [jordon31/OnlySnap#26]
Something in the API might have changed, but for some profiles, the source for videos are NoneType and it is impossible to download the videofile. Photos are all downloaded, video folder is empty.

**Comment by jordon31** [comment]
If on the creator's page there are videos with automatic quality, they are blob videos (DRM) and therefore it doesn't download them. At the moment, I haven't found any method.

**Comment by AnoCurly** [comment]
thanks for your information!
