### ISSUE TITLE
An error has occurred: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by Mspilotti** [jordon31/OnlySnap#27]
hi, i have this error:

An error has occurred: 'str' object does not support item assignment
Traceback (most recent call last):
  File "D:\downloads\OF\OF-SCR\OnlySnap\OnlySnap.py", line 816, in <module>
    SELECTED_MODELS = select_sub()
                      ^^^^^^^^^^^^
  File "D:\downloads\OF\OF-SCR\OnlySnap\OnlySnap.py", line 294, in select_sub
    SUBS = get_subs()
           ^^^^^^^^^^
  File "D:\downloads\OF\OF-SCR\OnlySnap\OnlySnap.py", line 273, in get_subs
    sub['type'] = 'Payed'
    ~~~^^^^^^^^
TypeError: 'str' object does not support item assignment

Please try again.

**Comment by jordon31** [comment]
write me on telegram and send auth file

"https://t.me/ocst892"

**Comment by Mspilotti** [comment]
Solved, the problem was in the difference between the script's user agent and the browser's user agent. This difference was causing the web session within Chrome to close, and as a result, the session changed. Once this was modified, the scraping started working perfectly!
