### ISSUE TITLE
Missing Shebang Line

### ISSUE THREAD

**Issue by deimosian** [jordon31/OnlySnap#28]
Cannot be run directly from terminal (with `./OnlySnap.py`) due to missing a shebang line.

**Comment by jordon31** [comment]
linux?

**Comment by deimosian** [comment]
Yes, that's why the first line of onlyfans-dl was `#!/usr/bin/python3`

This is the shebang line and tells the system what program can run the script.

**Comment by jordon31** [comment]
I'll try to fix it.
