### ISSUE TITLE
Not picking up new subscriptions

### ISSUE THREAD

**Issue by hoppalotta2** [jordon31/OnlySnap#32]
I've subscribed to a handful of new subs and onlysnap isn't picking up any of them.  Anyone know why?

I've tried logging out and providing all new credentials.  That didn't fix it.

**Comment by RandomRainbow** [comment]
delete subs_cache.json file

**Comment by jordon31** [comment]
Yes.. I need to find a way that it updates automatically when a user subscribes to a new one.
