### ISSUE TITLE
Only download new items since a certain date

### ISSUE THREAD

**Issue by rogueralsha** [jordon31/OnlySnap#34]
I tend to download items, and then sort them out into other programs. Whenever I want to update I have to re-download everything, would it be possible to implement a date cutoff, so that only new content gets downloaded?

**Comment by jordon31** [comment]
I need to implement a cache for this.. that then downloads the new content.

**Comment by rogueralsha** [comment]
How do I make use of this?

**Comment by jordon31** [comment]
What?

**Comment by rogueralsha** [comment]
The ticket was closed saying it was completed, is this now the default behavior of the script, or do I need to enable an option to use it?

**Comment by Snolpix** [comment]
its default the saved cache profile no need edit.. for other settings check file config

**Comment by rogueralsha** [comment]
Thanks for the clarification, and for the change. I really appreciate it.
