### ISSUE TITLE
An error has occurred: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by EvilBlood** [jordon31/OnlySnap#35]
Since the update I get the following error:

An error has occurred: 'str' object does not support item assignment
Traceback (most recent call last):
  File "G:\OF\OF-SCR\OnlySnap.py", line 816, in <module>
    SELECTED_MODELS = select_sub()
  File "G:\OF\OF-SCR\OnlySnap.py", line 294, in select_sub
    SUBS = get_subs()
  File "G:\OF\OF-SCR\OnlySnap.py", line 273, in get_subs
    sub['type'] = 'Payed'
TypeError: 'str' object does not support item assignment

Please try again.

this loops until I cancel the program.

**Comment by Mspilotti** [comment]
i have the same error.

**Comment by cgg520449** [comment]
i have the same error.

**Comment by cgg520449** [comment]
> Since the update I get the following error:
> 
> An error has occurred: 'str' object does not support item assignment Traceback (most recent call last): File "G:\OF\OF-SCR\OnlySnap.py", line 816, in SELECTED_MODELS = select_sub() File "G:\OF\OF-SCR\OnlySnap.py", line 294, in select_sub SUBS = get_subs() File "G:\OF\OF-SCR\OnlySnap.py", line 273, in get_subs sub['type'] = 'Payed' TypeError: 'str' object does not support item assignment
> 
> Please try again.
> 
> this loops until I cancel the program.

OnlySnap.py  
808---> Change THIS 
 "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"

**Comment by EvilBlood** [comment]
> > Since the update I get the following error:
> > An error has occurred: 'str' object does not support item assignment Traceback (most recent call last): File "G:\OF\OF-SCR\OnlySnap.py", line 816, in SELECTED_MODELS = select_sub() File "G:\OF\OF-SCR\OnlySnap.py", line 294, in select_sub SUBS = get_subs() File "G:\OF\OF-SCR\OnlySnap.py", line 273, in get_subs sub['type'] = 'Payed' TypeError: 'str' object does not support item assignment
> > Please try again.
> > this loops until I cancel the program.
> 
> OnlySnap.py 808---> Change THIS "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"

worked, thank you

**Comment by spankmonkey69** [comment]
> > Since the update I get the following error:
> > An error has occurred: 'str' object does not support item assignment Traceback (most recent call last): File "G:\OF\OF-SCR\OnlySnap.py", line 816, in SELECTED_MODELS = select_sub() File "G:\OF\OF-SCR\OnlySnap.py", line 294, in select_sub SUBS = get_subs() File "G:\OF\OF-SCR\OnlySnap.py", line 273, in get_subs sub['type'] = 'Payed' TypeError: 'str' object does not support item assignment
> > Please try again.
> > this loops until I cancel the program.
> 
> OnlySnap.py 808---> Change THIS "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"

I'm having this same error, i have nothing on line 808 in onlysnap.py, and when i paste this in, it wont run at all, what can i do?

**Comment by jdown1** [comment]
Hi,

The lines are below, but what needs to be changed? Only the URL?

808 dynamic_rules = requests.get(
809 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()

I've tried changing 809 to:
'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
"https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json").json()

But still get the same error, please advice

**Comment by spankmonkey69** [comment]
> Hi,
> 
> The lines are below, but what needs to be changed? Only the URL?
> 
> 808 dynamic_rules = requests.get( 809 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
> 
> I've tried changing 809 to: 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json() "[https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json").json(](https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json%22).json()) "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json") But still get the same error, please advice

Download the current version, line 808 will have a URL, just replace it and it will work. I had issues as i didnt have the latest copy, once i got the latest one, its all good

**Comment by vanssen** [comment]
Hello, someone has managed to get it to work, I have followed the instructions but it still gives the same error

**Comment by cgg520449** [comment]
> Hello, someone has managed to get it to work, I have followed the instructions but it still gives the same error


OnlySnap.py
808-809

Delete old links: 
https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json

add NEW :
https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json

**Comment by cgg520449** [comment]
> Hi,
> 
> The lines are below, but what needs to be changed? Only the URL?
> 
> 808 dynamic_rules = requests.get( 809 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
> 
> I've tried changing 809 to: 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json() "[https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json").json(](https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json%22).json()) "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json") But still get the same error, please advice

OnlySnap.py
808-809

Delete old links:
https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json

add NEW :
https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json.

Only one link

**Comment by cgg520449** [comment]
dynamic_rules = requests.get('https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()

> Hi,
> 
> The lines are below, but what needs to be changed? Only the URL?
> 
> 808 dynamic_rules = requests.get( 809 'https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json').json()
> 
> I've tried changing 809 to: 'https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json() "[https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json").json(](https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json%22).json()) "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json") But still get the same error, please advice


808:
only one link:
----
![Snipaste_2024-01-12_13-54-16](https://github.com/jordon31/OnlySnap/assets/116888205/06bfdcb7-fd45-47b7-a200-202a72309e17)

dynamic_rules = requests.get('https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()

and 

updata your "Auth.json"

**Comment by jordon31** [comment]
hi all guys.. i'm updating this script.. wait new update
