### ISSUE TITLE
ERROR: Please refresh the pag

### ISSUE THREAD

**Issue by rhcp011235** [jordon31/OnlySnap#36]
Never seen this before and I don’t see a way to debug it.

but I get the error ERROR: Please refresh the pag

**Comment by St0RM53** [comment]
i get ERROR: Access denied. with no other error, updated useragent and session cookie ;/

**Comment by St0RM53** [comment]
ok i re-login new cookie, i get same error as you now

**Comment by spankmonkey69** [comment]
I have this same error, any fix?

**Comment by jordon31** [comment]
i fix this with other update
