### ISSUE TITLE
warnings 

### ISSUE THREAD

**Issue by sammas72** [jordon31/OnlySnap#38]
Hi,
 the script send me this warning. Sorry I'm a beginners, so easily I can wrong something

Warning (from warnings module):
  File "C:\Users\s.amista\Downloads\OnlySnap-main\OnlySnap-main\OnlySnap.py", line 353
    file_type = re.findall("\.\w+", source)[-1]
SyntaxWarning: invalid escape sequence '\.'
>>> 
Warning (from warnings module):
  File "C:\Users\s.amista\Downloads\OnlySnap-main\OnlySnap-main\OnlySnap.py", line 414
    ext = re.findall('\.\w+\?', source)
SyntaxWarning: invalid escape sequence '\.'
>>> 
Warning (from warnings module):
  File "C:\Users\s.amista\Downloads\OnlySnap-main\OnlySnap-main\OnlySnap.py", line 506
    ext = re.findall('\.\w+\?', source)
SyntaxWarning: invalid escape sequence '\.'
>>> 
= RESTART: C:\Users\s.amista\Downloads\OnlySnap-main\OnlySnap-main\OnlySnap.py
Traceback (most recent call last):
  File "C:\Users\s.amista\Downloads\OnlySnap-main\OnlySnap-main\OnlySnap.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by rhcp011235** [comment]
Read the manual.

pip install requests
pip3 install requests




IMPORTANT: This email message is intended only for the use of the
individual to whom, or entity to which, it is addressed and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law. If you are NOT the intended recipient, you are hereby
notified that any use, dissemination, distribution or copying of this
communication is strictly prohibited.  If you have received this
communication in error, please reply to the sender immediately and
permanently delete this email.
