### ISSUE TITLE
An error has occurred: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by xlvno123** [jordon31/OnlySnap#39]
An error has occurred: string indices must be integers, not 'str'
Traceback (most recent call last):
  File "E:\OnlySnap.py", line 871, in <module>
    photo_posts = get_all_photos(photos)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OnlySnap.py", line 686, in get_all_photos
    getdata={"limit": "999999", "order": "publish_date_desc", "beforePublishTime": images[-1]["postedAtPrecise"] if images else None},
                                                                                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Please try again.

**Comment by cgg520449** [comment]
808:

dynamic_rules = requests.get('https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()

and

updata your "Auth.json"
![Snipaste_2024-01-12_13-54-16](https://github.com/jordon31/OnlySnap/assets/116888205/a606147f-2397-481f-99df-2060ce608b61)

**Comment by UWPA** [comment]
> 808:
> 
> dynamic_rules = requests.get('https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json').json()
> 
> and
> 
> updata your "Auth.json"
> 
> ![Snipaste_2024-01-12_13-54-16](https://private-user-images.githubusercontent.com/116888205/296142425-a606147f-2397-481f-99df-2060ce608b61.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDM1NjEsIm5iZiI6MTcwNTQ0MzI2MSwicGF0aCI6Ii8xMTY4ODgyMDUvMjk2MTQyNDI1LWE2MDYxNDdmLTIzOTctNDgxZi05OWRmLTIwNjBjZTYwOGI2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGRlNjhjMGE3YjVhYWZmNzRiMzMwNjUyYWY4OTY3MTk2ZDI5NDkyMjdlYjJhNDYzZWJiNGM4YTQ0ZDVhNTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nKY-9Nto1d1hsI8CrZSEstNVAgIHJ5Bh82xhuxj5tFw)

Doesn't seem to fix the issue.

**Comment by jordon31** [comment]
This looks like another mistake.. Can you tell me the creator's name? Is it free?

**Comment by jordon31** [comment]
> An error has occurred: string indices must be integers, not 'str' Traceback (most recent call last): File "E:\OnlySnap.py", line 871, in photo_posts = get_all_photos(photos) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\OnlySnap.py", line 686, in get_all_photos getdata={"limit": "999999", "order": "publish_date_desc", "beforePublishTime": images[-1]["postedAtPrecise"] if images else None}, ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^ TypeError: string indices must be integers, not 'str'
> 
> Please try again.

This looks like another mistake.. Can you tell me the creator's name? Is it free?
