### ISSUE TITLE
str bug

### ISSUE THREAD

**Issue by jadenquinn** [jordon31/OnlySnap#43]
I got this error when I start it up:
https://pastebin.com/6n6uiZRt

**Comment by nenya1840** [comment]
change from
`https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`
to
`https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json`

**Comment by jordon31** [comment]
fixed with next update.. soon

**Comment by jordon31** [comment]
updated @jadenquinn
