### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by cgg520449** [jordon31/OnlySnap#45]
Everything was normal last week, but today I found that it is not working. Is there a way to fix it? Thank you.

![Snipaste_2024-06-07_17-46-33](https://github.com/jordon31/OnlySnap/assets/116888205/c4d84b38-2fc7-4845-aa78-1c8066428b34)

**Comment by cgg520449** [comment]
> 我也發生了

Good thing, can confirm it's not my setting error.
Bad thing, need  fix

**Comment by w13ldz** [comment]
i got:

ERROR: Please refresh the page

**Comment by Hallimede** [comment]
> i got:
> 
> ERROR: Please refresh the page

This should be solved when dynamic_rules is updated which is getting from https://github.com/deviint/onlyfans-dynamic-rules. There is a pull request that has not been merged yet currenly.

**Comment by jordon31** [comment]
Hello sorry for delay.. i dont check my account github.. for any report.. pls join on telegram

**Comment by jordon31** [comment]
for now its fixed

**Comment by jordon31** [comment]
@cgg520449 @Hallimede @MO111111111 @w13ldz
